server.port: 9090
spring:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/m-295-app
    username: postgres
    password: admin
    driverClassName: org.postgresql.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/ILV

springdoc:
  swagger-ui:
    path: /
    operationsSorter: method
    tagsSorter: alpha
  api-docs:
    path: /api-docs